version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: psychsupport-postgres
    environment:
      POSTGRES_DB: db_1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - psychsupport-network
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: psychsupport-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db_1
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - psychsupport-network
    restart: unless-stopped

networks:
  psychsupport-network:
    driver: bridge

volumes:
  postgres-data:
